### ISSUE TITLE
cannot read property stateNode of undefined.

### ISSUE THREAD

**Issue by aerohh** [codeherence/react-native-header#9] opened 2023-03-30 08:15 UTC
## Description

The error seems to be in the file `fabricUtils.ts` and only triggers when `FlatListWithHeaders` is used.

## Dependencies

"@codeherence/react-native-header": "^0.7.2",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@react-native-community/datetimepicker": "^7.0.0",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@wuba/react-native-echarts": "^1.0.0",
    "echarts": "^5.4.2",
    "geolib": "^3.3.3",
    "i18next": "^22.4.11",
    "react": "18.2.0",
    "react-i18next": "^12.2.0",
    "react-native": "0.71.4",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-get-location": "^3.0.1",
    "react-native-modal-datetime-picker": "^14.0.1",
    "react-native-pager-view": "^6.1.4",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "^3.0.2",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "^13.8.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-timeline-flatlist": "^0.8.0",
    "react-native-toast-message": "^2.1.6"

**Comment by e-younan** [comment] 2023-03-30 08:18
Thanks for the bug report. Can you provide more context on what the error is?

**Comment by e-younan** [comment] 2023-03-30 08:22
This seems to relate to [react-native-reanimated#3534](https://github.com/software-mansion/react-native-reanimated/issues/3534) and [react-native-reanimated#4256](https://github.com/software-mansion/react-native-reanimated/issues/4256). Can you provide some code relating to how you're using the library?

**Comment by fgagneten** [comment] 2023-03-30 13:46
This issue is related to Gorhom library I guess. Look at this comment: https://github.com/gorhom/react-native-bottom-sheet/pull/1324#issuecomment-1490334608

**Comment by e-younan** [comment] 2023-03-30 16:26
> This issue is related to Gorhom library I guess. Look at this comment: https://github.com/gorhom/react-native-bottom-sheet/pull/1324#issuecomment-1490334608

Thanks for flagging - I will close this issue. @aerohh feel free to re-open if the issue is specifically related to the library.

**Closed** 2023-03-30 16:26 UTC
Labels: bug
